#coding:utf-8
import logging
import util.opreation_gloabal_var as Ogv
def a(new_dict,key=None):
    if type(new_dict) == dict:
        for key in new_dict:
            a(new_dict[key],key)
    if type(new_dict) == list:
        for i in new_dict:
            a(i)
    if str(new_dict) == 'None':
        print(key+'----------------------'+'')
    if type(new_dict) == str:
        print(key+'----------------------'+new_dict)

aa = {
    "code": "0000",
    "message": "处理成功",
    "data": {
        "invoiceListFrontLists": None,
        "notReadInvoiceFrontList": None,
        "readInvoiceFrontList": [
            {
                "invoiceinfo_id": "04fd3a88-cbd0-47f2-a1b5-39e77dfabe56",
                "read_status": "1",
                "table_type": None,
                "kpxm": None,
                "jym": None,
                "existPdf": "1",
                "todoLabel": None,
                "isRemind": None,
                "route": "了-啊",
                "train": "g2",
                "shareName": None,
                "hjje": None,
                "table_TYPE": None,
                "cyzt": None,
                "bxzt": None,
                "ydzt": None,
                "pdf_FILE": None,
                "png_FILE": None,
                "paper_IMG_FILE": None,
                "check_STATUS": None,
                "fplb": "2",
                "fplx": None,
                "xsf_MC": None,
                "gmf_MC": None,
                "kprq": "2021-02-08 12:02:00",
                "sqrq": "2018-02-08 22:16:01",
                "jshj": "55",
                "fp_DM": None,
                "fp_HM": None,
                "kjzt": None,
                "ele_PDF_PATH": "2b167b4e-2ac0-49c3-b288-ba0cfc068ea4"
            },
            {
                "invoiceinfo_id": "d2c2f10e-b3ee-4bf0-98ec-d3fe512ce614",
                "read_status": "0",
                "table_type": None,
                "kpxm": None,
                "jym": None,
                "existPdf": "0",
                "todoLabel": None,
                "isRemind": None,
                "route": None,
                "train": None,
                "shareName": None,
                "hjje": None,
                "table_TYPE": None,
                "cyzt": None,
                "bxzt": None,
                "ydzt": None,
                "pdf_FILE": None,
                "png_FILE": None,
                "paper_IMG_FILE": None,
                "check_STATUS": None,
                "fplb": "3",
                "fplx": None,
                "xsf_MC": None,
                "gmf_MC": None,
                "kprq": "2018-02-08 12:02:00",
                "sqrq": "2018-02-08 22:16:01",
                "jshj": "55",
                "fp_DM": None,
                "fp_HM": None,
                "kjzt": None,
                "ele_PDF_PATH": None
            },
            {
                "invoiceinfo_id": "159f6f8cddc641dfb15b542be71110c6",
                "read_status": "1",
                "table_type": "0",
                "kpxm": "JavaScriptDOM编程艺术（第2版）",
                "jym": "76958721052898882542",
                "existPdf": "1",
                "todoLabel": None,
                "isRemind": None,
                "route": None,
                "train": None,
                "shareName": None,
                "hjje": "103.70",
                "table_TYPE": None,
                "cyzt": None,
                "bxzt": "0",
                "ydzt": None,
                "pdf_FILE": None,
                "png_FILE": None,
                "paper_IMG_FILE": None,
                "check_STATUS": "1",
                "fplb": "0",
                "fplx": None,
                "xsf_MC": "江苏圆周电子商务有限公司上海分公司",
                "gmf_MC": None,
                "kprq": "2017-10-26 00:00:00",
                "sqrq": "2018-02-08 22:15:53",
                "jshj": "103.70",
                "fp_DM": "031001700111",
                "fp_HM": "02350665",
                "kjzt": None,
                "ele_PDF_PATH": "3598578f-ff14-41fa-9188-3a1702ba5cb8"
            },
            {
                "invoiceinfo_id": "b2d135b5-534d-418f-a4b1-bed2c8da1d75",
                "read_status": "1",
                "table_type": None,
                "kpxm": None,
                "jym": None,
                "existPdf": "0",
                "todoLabel": None,
                "isRemind": None,
                "route": None,
                "train": None,
                "shareName": None,
                "hjje": None,
                "table_TYPE": None,
                "cyzt": None,
                "bxzt": None,
                "ydzt": None,
                "pdf_FILE": None,
                "png_FILE": None,
                "paper_IMG_FILE": None,
                "check_STATUS": None,
                "fplb": "3",
                "fplx": None,
                "xsf_MC": None,
                "gmf_MC": None,
                "kprq": "2018-02-08 12:02:00",
                "sqrq": "2018-02-08 22:15:53",
                "jshj": "55",
                "fp_DM": None,
                "fp_HM": None,
                "kjzt": None,
                "ele_PDF_PATH": None
            },
            {
                "invoiceinfo_id": "f90e52b1-6f49-422a-8670-cd7bc9ed0ec3",
                "read_status": "1",
                "table_type": None,
                "kpxm": None,
                "jym": None,
                "existPdf": "1",
                "todoLabel": None,
                "isRemind": None,
                "route": "了-啊",
                "train": "g2",
                "shareName": None,
                "hjje": None,
                "table_TYPE": None,
                "cyzt": None,
                "bxzt": None,
                "ydzt": None,
                "pdf_FILE": None,
                "png_FILE": None,
                "paper_IMG_FILE": None,
                "check_STATUS": None,
                "fplb": "2",
                "fplx": None,
                "xsf_MC": None,
                "gmf_MC": None,
                "kprq": "2021-02-08 12:02:00",
                "sqrq": "2018-02-08 22:15:53",
                "jshj": "55",
                "fp_DM": None,
                "fp_HM": None,
                "kjzt": None,
                "ele_PDF_PATH": "2b167b4e-2ac0-49c3-b288-ba0cfc068ea4"
            },
            {
                "invoiceinfo_id": "4d4887aa-d47f-428c-9376-202401c08189",
                "read_status": "1",
                "table_type": "0",
                "kpxm": "",
                "jym": "61967127240133149728",
                "existPdf": "1",
                "todoLabel": None,
                "isRemind": None,
                "route": None,
                "train": None,
                "shareName": None,
                "hjje": "1964.96",
                "table_TYPE": None,
                "cyzt": None,
                "bxzt": "0",
                "ydzt": None,
                "pdf_FILE": None,
                "png_FILE": None,
                "paper_IMG_FILE": None,
                "check_STATUS": "0",
                "fplb": "0",
                "fplx": None,
                "xsf_MC": "华为终端（东莞）有限公司",
                "gmf_MC": None,
                "kprq": "2016-08-23 00:00:00",
                "sqrq": "2018-02-08 21:26:23",
                "jshj": "2299.0",
                "fp_DM": "044001611111",
                "fp_HM": "12385436",
                "kjzt": None,
                "ele_PDF_PATH": None
            },
            {
                "invoiceinfo_id": "935691212323684352",
                "read_status": "1",
                "table_type": "0",
                "kpxm": "Snowkids 苹果MFi认证6/5s/7数据线 1.5米手机快充充电器线USB电源线 支持iPhone6s/7P/SE/iPad io",
                "jym": "80947885001587938413",
                "existPdf": "1",
                "todoLabel": None,
                "isRemind": None,
                "route": None,
                "train": None,
                "shareName": None,
                "hjje": "47.29",
                "table_TYPE": None,
                "cyzt": None,
                "bxzt": "0",
                "ydzt": None,
                "pdf_FILE": None,
                "png_FILE": None,
                "paper_IMG_FILE": None,
                "check_STATUS": "1",
                "fplb": "0",
                "fplx": None,
                "xsf_MC": "上海圆迈贸易有限公司",
                "gmf_MC": None,
                "kprq": "2017-09-13 00:00:00",
                "sqrq": "2018-02-08 21:10:26",
                "jshj": "55.32",
                "fp_DM": "031001700111",
                "fp_HM": "13536187",
                "kjzt": None,
                "ele_PDF_PATH": None
            },
            {
                "invoiceinfo_id": "4e6f92efbe184863b2371122390b02d0",
                "read_status": "1",
                "table_type": "0",
                "kpxm": "荣耀V8全网通4GB+64GB铂光金移动联通电信4G手机双卡双待双通",
                "jym": "71052505460439498589",
                "existPdf": "1",
                "todoLabel": "保修",
                "isRemind": "0",
                "route": None,
                "train": None,
                "shareName": None,
                "hjje": "1281.58",
                "table_TYPE": None,
                "cyzt": None,
                "bxzt": "0",
                "ydzt": None,
                "pdf_FILE": None,
                "png_FILE": None,
                "paper_IMG_FILE": None,
                "check_STATUS": "1",
                "fplb": "0",
                "fplx": None,
                "xsf_MC": "廊坊京东友盛贸易有限公司",
                "gmf_MC": None,
                "kprq": "2017-12-03 00:00:00",
                "sqrq": "2018-02-08 21:08:05",
                "jshj": "1499.44",
                "fp_DM": "013001620011",
                "fp_HM": "11993393",
                "kjzt": None,
                "ele_PDF_PATH": "f61b3404-2dd5-459c-9197-9713c94a92f1"
            },
            {
                "invoiceinfo_id": "ac3b7610-0708-4419-ad15-6e5f9994b554",
                "read_status": "1",
                "table_type": None,
                "kpxm": None,
                "jym": None,
                "existPdf": "1",
                "todoLabel": "在搞么感|啦啦啦啦",
                "isRemind": None,
                "route": "摸摸哦-默默无闻我",
                "train": "g2",
                "shareName": None,
                "hjje": None,
                "table_TYPE": None,
                "cyzt": None,
                "bxzt": None,
                "ydzt": None,
                "pdf_FILE": None,
                "png_FILE": None,
                "paper_IMG_FILE": None,
                "check_STATUS": None,
                "fplb": "2",
                "fplx": None,
                "xsf_MC": None,
                "gmf_MC": None,
                "kprq": "2018-02-08 12:02:00",
                "sqrq": "2018-02-08 19:27:19",
                "jshj": "38888",
                "fp_DM": None,
                "fp_HM": None,
                "kjzt": None,
                "ele_PDF_PATH": "81261ccf-9a33-41cc-92c9-954b9b36be03"
            },
            {
                "invoiceinfo_id": "baf143e1-5a11-47da-9f43-362659f8f884",
                "read_status": "1",
                "table_type": None,
                "kpxm": None,
                "jym": None,
                "existPdf": "1",
                "todoLabel": "在搞么感|啦啦啦啦",
                "isRemind": None,
                "route": None,
                "train": None,
                "shareName": None,
                "hjje": None,
                "table_TYPE": None,
                "cyzt": None,
                "bxzt": None,
                "ydzt": None,
                "pdf_FILE": None,
                "png_FILE": None,
                "paper_IMG_FILE": None,
                "check_STATUS": None,
                "fplb": "3",
                "fplx": None,
                "xsf_MC": None,
                "gmf_MC": None,
                "kprq": "2018-02-08 12:02:00",
                "sqrq": "2018-02-08 19:27:05",
                "jshj": "36996",
                "fp_DM": None,
                "fp_HM": None,
                "kjzt": None,
                "ele_PDF_PATH": "066b6af7-568d-4042-9d16-a9aed12a80ea"
            },
            {
                "invoiceinfo_id": "0d630651-038f-4df0-a42b-f974792f7bca",
                "read_status": "1",
                "table_type": "0",
                "kpxm": "西部数据（WD）My Passport Ultra 升级版 1TB 2.5英寸 经典黑 移动硬盘 WDBGPU0010BBK",
                "jym": "65839937913493506721",
                "existPdf": "1",
                "todoLabel": None,
                "isRemind": None,
                "route": None,
                "train": None,
                "shareName": None,
                "hjje": "383.76",
                "table_TYPE": None,
                "cyzt": None,
                "bxzt": "0",
                "ydzt": None,
                "pdf_FILE": None,
                "png_FILE": None,
                "paper_IMG_FILE": None,
                "check_STATUS": "0",
                "fplb": "0",
                "fplx": None,
                "xsf_MC": "杭州京东惠景贸易有限公司",
                "gmf_MC": None,
                "kprq": "2016-11-21 00:00:00",
                "sqrq": "2018-02-08 17:54:44",
                "jshj": "449.0",
                "fp_DM": "033001600211",
                "fp_HM": "41787157",
                "kjzt": None,
                "ele_PDF_PATH": None
            },
            {
                "invoiceinfo_id": "a874c468-7e78-4c2b-8083-de740dcc757c",
                "read_status": "1",
                "table_type": "0",
                "kpxm": "华硕（ASUS）RT-AC68U 1900M AC双频 低辐射 智能无线路由器",
                "jym": "62736412134219892610",
                "existPdf": "1",
                "todoLabel": "啦啦啦啦|在搞么感",
                "isRemind": "0",
                "route": None,
                "train": None,
                "shareName": None,
                "hjje": "562.4",
                "table_TYPE": None,
                "cyzt": None,
                "bxzt": "0",
                "ydzt": None,
                "pdf_FILE": None,
                "png_FILE": None,
                "paper_IMG_FILE": None,
                "check_STATUS": "0",
                "fplb": "0",
                "fplx": None,
                "xsf_MC": "上海圆迈贸易有限公司",
                "gmf_MC": None,
                "kprq": "2018-01-03 00:00:00",
                "sqrq": "2018-01-03 17:02:43",
                "jshj": "658.0",
                "fp_DM": "031001700311",
                "fp_HM": "18439955",
                "kjzt": None,
                "ele_PDF_PATH": None
            },
            {
                "invoiceinfo_id": "1d22d3a1-d349-4a14-a28c-c4f9105e5e6c",
                "read_status": "1",
                "table_type": None,
                "kpxm": None,
                "jym": None,
                "existPdf": "1",
                "todoLabel": "",
                "isRemind": "0",
                "route": "错-来来来",
                "train": "K521",
                "shareName": None,
                "hjje": None,
                "table_TYPE": None,
                "cyzt": None,
                "bxzt": None,
                "ydzt": None,
                "pdf_FILE": None,
                "png_FILE": None,
                "paper_IMG_FILE": None,
                "check_STATUS": None,
                "fplb": "2",
                "fplx": None,
                "xsf_MC": None,
                "gmf_MC": None,
                "kprq": "2017-12-26 12:12:00",
                "sqrq": "2017-12-26 17:51:36",
                "jshj": "99",
                "fp_DM": None,
                "fp_HM": None,
                "kjzt": None,
                "ele_PDF_PATH": "c02913d4-d8f9-4bbb-ba85-1979f5c74ffa"
            },
            {
                "invoiceinfo_id": "8590ca02-bf61-4ca4-9456-c9449665af2b",
                "read_status": "1",
                "table_type": None,
                "kpxm": None,
                "jym": None,
                "existPdf": "0",
                "todoLabel": None,
                "isRemind": None,
                "route": "苏州北-1111",
                "train": "K520",
                "shareName": None,
                "hjje": None,
                "table_TYPE": None,
                "cyzt": None,
                "bxzt": None,
                "ydzt": None,
                "pdf_FILE": None,
                "png_FILE": None,
                "paper_IMG_FILE": None,
                "check_STATUS": None,
                "fplb": "2",
                "fplx": None,
                "xsf_MC": None,
                "gmf_MC": None,
                "kprq": "2017-12-22 12:12:00",
                "sqrq": "2017-12-22 10:06:15",
                "jshj": "99",
                "fp_DM": None,
                "fp_HM": None,
                "kjzt": None,
                "ele_PDF_PATH": ""
            },
            {
                "invoiceinfo_id": "13593c6c-b677-4332-aa36-6bff90f5a9aa",
                "read_status": "0",
                "table_type": None,
                "kpxm": None,
                "jym": None,
                "existPdf": "0",
                "todoLabel": "在搞么感|啦啦啦啦",
                "isRemind": None,
                "route": "苏州北-aaaa",
                "train": "K520",
                "shareName": None,
                "hjje": None,
                "table_TYPE": None,
                "cyzt": None,
                "bxzt": None,
                "ydzt": None,
                "pdf_FILE": None,
                "png_FILE": None,
                "paper_IMG_FILE": None,
                "check_STATUS": None,
                "fplb": "2",
                "fplx": None,
                "xsf_MC": None,
                "gmf_MC": None,
                "kprq": "2017-12-22 12:12:00",
                "sqrq": "2017-12-22 10:05:51",
                "jshj": "99",
                "fp_DM": None,
                "fp_HM": None,
                "kjzt": None,
                "ele_PDF_PATH": ""
            },
            {
                "invoiceinfo_id": "12a6379c366349878a62273ea02514b6",
                "read_status": "1",
                "table_type": "0",
                "kpxm": "AppleiPad平板电脑9.7英寸（32GWLAN版/A9芯片/Retina显示屏/TouchID技术MP2G2CH/A）银色",
                "jym": "45051176502614354702",
                "existPdf": "1",
                "todoLabel": None,
                "isRemind": None,
                "route": None,
                "train": None,
                "shareName": None,
                "hjje": "2053.42",
                "table_TYPE": None,
                "cyzt": None,
                "bxzt": "0",
                "ydzt": None,
                "pdf_FILE": None,
                "png_FILE": None,
                "paper_IMG_FILE": None,
                "check_STATUS": "0",
                "fplb": "0",
                "fplx": None,
                "xsf_MC": "上海圆迈贸易有限公司",
                "gmf_MC": None,
                "kprq": "2017-04-29 00:00:00",
                "sqrq": "2017-12-20 15:14:17",
                "jshj": "2402.50",
                "fp_DM": "031001600411",
                "fp_HM": "25057828",
                "kjzt": None,
                "ele_PDF_PATH": "6f9022a3-05a7-4ef5-a2be-a48bfe9602e7"
            },
            {
                "invoiceinfo_id": "933667324907618304",
                "read_status": "1",
                "table_type": "0",
                "kpxm": "通信服务费",
                "jym": "12798779261036224214",
                "existPdf": "0",
                "todoLabel": "啦啦啦啦|在搞么感",
                "isRemind": None,
                "route": None,
                "train": None,
                "shareName": None,
                "hjje": "-91.01",
                "table_TYPE": None,
                "cyzt": None,
                "bxzt": "0",
                "ydzt": None,
                "pdf_FILE": None,
                "png_FILE": None,
                "paper_IMG_FILE": None,
                "check_STATUS": "1",
                "fplb": "0",
                "fplx": None,
                "xsf_MC": "中国联合网络通信有限公司北京市分公司",
                "gmf_MC": None,
                "kprq": "2017-08-03 00:00:00",
                "sqrq": "2017-11-29 09:36:01",
                "jshj": "-91.01",
                "fp_DM": "011001600211",
                "fp_HM": "37855222",
                "kjzt": None,
                "ele_PDF_PATH": None
            },
            {
                "invoiceinfo_id": "83c5f5be43df4d8988c20e9f69a3e723",
                "read_status": "1",
                "table_type": "0",
                "kpxm": "餐饮费",
                "jym": "66111395301624570378",
                "existPdf": "1",
                "todoLabel": None,
                "isRemind": None,
                "route": None,
                "train": None,
                "shareName": None,
                "hjje": "424.53",
                "table_TYPE": None,
                "cyzt": None,
                "bxzt": "0",
                "ydzt": None,
                "pdf_FILE": None,
                "png_FILE": None,
                "paper_IMG_FILE": None,
                "check_STATUS": "1",
                "fplb": "0",
                "fplx": None,
                "xsf_MC": "北京湄州三苏大酒楼有限公司",
                "gmf_MC": None,
                "kprq": "2017-02-21 00:00:00",
                "sqrq": "2017-11-28 11:35:30",
                "jshj": "450.00",
                "fp_DM": "011001600111",
                "fp_HM": "07865893",
                "kjzt": None,
                "ele_PDF_PATH": "35809ac3-3e3d-45e9-bf22-4c9ef2202eaa"
            },
            {
                "invoiceinfo_id": "31d6067c186e49cab5e9a1001d72e4f6",
                "read_status": "1",
                "table_type": "0",
                "kpxm": "餐饮服务",
                "jym": "53449674053628669386",
                "existPdf": "1",
                "todoLabel": "啦啦啦啦|在搞么感",
                "isRemind": None,
                "route": None,
                "train": None,
                "shareName": None,
                "hjje": "13.21",
                "table_TYPE": None,
                "cyzt": None,
                "bxzt": "0",
                "ydzt": None,
                "pdf_FILE": None,
                "png_FILE": None,
                "paper_IMG_FILE": None,
                "check_STATUS": "0",
                "fplb": "0",
                "fplx": None,
                "xsf_MC": "无锡麦当劳餐厅食品有限公司",
                "gmf_MC": None,
                "kprq": "2017-08-13 00:00:00",
                "sqrq": "2017-11-28 11:33:56",
                "jshj": "14.00",
                "fp_DM": "032001600111",
                "fp_HM": "01253111",
                "kjzt": None,
                "ele_PDF_PATH": "e836af3d-07fc-4453-8317-5b46a185b1d7"
            },
            {
                "invoiceinfo_id": "933678175676923904",
                "read_status": "1",
                "table_type": "0",
                "kpxm": "技术开发费",
                "jym": "54364878851103401094",
                "existPdf": "1",
                "todoLabel": None,
                "isRemind": None,
                "route": None,
                "train": None,
                "shareName": None,
                "hjje": "23584.91",
                "table_TYPE": None,
                "cyzt": None,
                "bxzt": "0",
                "ydzt": None,
                "pdf_FILE": None,
                "png_FILE": None,
                "paper_IMG_FILE": None,
                "check_STATUS": "1",
                "fplb": "1",
                "fplx": None,
                "xsf_MC": "苏州安软信息科技有限公司",
                "gmf_MC": None,
                "kprq": "2017-06-12 00:00:00",
                "sqrq": "2017-11-23 22:46:41",
                "jshj": "25000.0",
                "fp_DM": "3200163130",
                "fp_HM": "15895067",
                "kjzt": None,
                "ele_PDF_PATH": None
            }
        ],
        "cxcs": None,
        "fplb": "None",
        "kjzt": None,
        "cxrq": "None",
        "zje": "109240.95",
        "zse": "2511.20",
        "zsl": "20"
    }
}
#a(aa)

class ma:
    def __init__(self,new_dict):
        self.new_dict = new_dict
    def deal_data(self,data,key=None,target_data=None):

        if type(data) == dict:
            for key in data:
                self.deal_data(data[key], key)
        if type(data) == list:
            for i in data:
                self.deal_data(i)
        #if type(data) == str:
        if type(data) == str:
            self.new_dict[key] = data
        if str(data) == 'None':
            self.new_dict[key] = ''
        return self.new_dict

ma = ma({})

print(ma.deal_data(aa))

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)



handler = logging.FileHandler('test.log')
handler.setLevel(logging.INFO)

formatter = logging.Formatter('%(asctime)s - %(name)s - %(levelname)s - %(message)s')
handler.setFormatter(formatter)

logger.info('start reading database')

logger.addHandler(handler)


import  util.opreation_excel

from main.execute_one_case import Execute

exc = Execute()
exc.case_inset('q','q','q','q','q','q','q','q',',','q','q','q','q','q','q')
